#!/usr/bin/env bash
# GENERALIZED lineage-sidecar attachment. Emits (to stdout) a complete manifest —
# lineage ConfigMap + Service + Deployment — that runs ANY app image with:
#   (a) arielf's lineage sidecar (proxy-init initContainer + envoy-proxy sidecar,
#       AuthBridge envoy-sidecar mode, capture_io:true, no auth/SPIRE), and
#   (b) the propagate-only OTEL shim launcher wrapping the app command
#       (--traces_exporter none: export nothing, only propagate traceparent).
#
# Supersedes the trivia-specific trivia-experiment.yaml. Per app, only a handful
# of variables change (image + self_id + the app's own entrypoint + LLM env).
#
# Usage (pipe to kubectl apply):
#   NAME=a2a-currency-converter \
#   IMAGE=docker.io/library/a2a_currency_converter-otel:latest \
#   APP_PORT=8000 SVC_PORT=8080 \
#   APP_ENTRYPOINT='app --host 0.0.0.0 --port 8000' \
#   ENV_VARS='LLM_API_BASE=http://host.containers.internal:11434/v1 LLM_MODEL=qwen2.5:7b LLM_API_KEY=ollama' \
#   lineage-sidecar/attach-lineage.sh | kubectl apply -f -
#
# Variables:
#   NAME               (required) k8s resource name + app.kubernetes.io/name label.
#   IMAGE              (required) the -otel wrapper image (build-otel-shim.sh output).
#   SELF_ID            lineage self_id (default: NAME). Only this varies in the config.
#   APP_PORT           app container port (default 8000).
#   SVC_PORT           service port (default 8080).
#   APP_ENTRYPOINT     the app's OWN command tokens that replace trivia's `server`
#                      (default 'server'). Check the app image's Dockerfile CMD,
#                      dropping any leading `uv run --no-sync`.
#   ENV_VARS           space-separated KEY=VALUE app env (LLM_* etc). Values must
#                      not contain spaces (fine for our URLs/models). May include
#                      OTEL_SERVICE_NAME to override the default (SELF_ID).
#   OUTBOUND_PORTS_EXCLUDE  iptables outbound excludes (default ''). Set to an
#                      app's OWN OTLP export port (e.g. 8335/4318) for an app that
#                      already exports spans, so that export keeps flowing
#                      untouched. Do NOT exclude LLM/tool ports — we want those seen.
#   NAMESPACE          (default team1).
#   KAGENTI_TYPE       kagenti.io/type label: agent | tool (default agent).
#   NO_OTEL            if set to 1, run the app command bare (no opentelemetry-
#                      instrument wrapper) — for a baseline/uninstrumented run.
set -euo pipefail

NAME="${NAME:?set NAME}"
IMAGE="${IMAGE:?set IMAGE}"
SELF_ID="${SELF_ID:-$NAME}"
APP_PORT="${APP_PORT:-8000}"
SVC_PORT="${SVC_PORT:-8080}"
APP_ENTRYPOINT="${APP_ENTRYPOINT:-server}"
ENV_VARS="${ENV_VARS:-}"
OUTBOUND_PORTS_EXCLUDE="${OUTBOUND_PORTS_EXCLUDE:-}"
NAMESPACE="${NAMESPACE:-team1}"
KAGENTI_TYPE="${KAGENTI_TYPE:-agent}"
NO_OTEL="${NO_OTEL:-0}"

# ---- build the container command array (YAML flow sequence) ----
otel_prefix='"uv","run","--no-sync","opentelemetry-instrument","--traces_exporter","none","--metrics_exporter","none","--logs_exporter","none"'
app_tokens=""
for tok in $APP_ENTRYPOINT; do app_tokens="${app_tokens}\"${tok}\","; done
app_tokens="${app_tokens%,}"
if [ "$NO_OTEL" = "1" ]; then
  CMD_ARRAY="[${app_tokens}]"
else
  CMD_ARRAY="[${otel_prefix},${app_tokens}]"
fi

# ---- build env block ----
# propagate-only OTEL env is always present (harmless when NO_OTEL, ignored).
env_block=$(cat <<EOF
            - { name: OTEL_TRACES_EXPORTER,  value: "none" }
            - { name: OTEL_METRICS_EXPORTER, value: "none" }
            - { name: OTEL_LOGS_EXPORTER,    value: "none" }
            - { name: OTEL_PROPAGATORS,      value: "tracecontext,baggage" }
            - { name: PORT, value: "${APP_PORT}" }
            - { name: HOST, value: "0.0.0.0" }
            # HOME=/tmp + UV_NO_CACHE: uv run --no-sync execs from the existing
            # venv and needs no cache; disabling the cache entirely sidesteps
            # every cache-dir-not-writable-for-UID-1001 variant (images chown
            # /app differently, and some pre-seed a root-owned /tmp/uv-cache).
            - { name: HOME, value: "/tmp" }
            - { name: UV_NO_CACHE, value: "1" }
EOF
)
# OTEL_SERVICE_NAME defaults to SELF_ID; skip the default when the caller
# supplies one via ENV_VARS so the caller's value wins (no duplicate entry).
case " $ENV_VARS" in
  *" OTEL_SERVICE_NAME="*) ;;
  *) env_block="${env_block}
            - { name: OTEL_SERVICE_NAME,     value: \"${SELF_ID}\" }" ;;
esac
for kv in $ENV_VARS; do
  k="${kv%%=*}"; v="${kv#*=}"
  env_block="${env_block}
            - { name: ${k}, value: \"${v}\" }"
done

# ---- proxy-init OUTBOUND_PORTS_EXCLUDE env (only if set) ----
exclude_env=""
if [ -n "$OUTBOUND_PORTS_EXCLUDE" ]; then
  exclude_env="
            - name: OUTBOUND_PORTS_EXCLUDE
              value: \"${OUTBOUND_PORTS_EXCLUDE}\""
fi

cat <<EOF
# GENERATED by lineage-sidecar/attach-lineage.sh — do not hand-edit; re-run.
# app=${NAME} self_id=${SELF_ID} image=${IMAGE} otel=$([ "$NO_OTEL" = 1 ] && echo off || echo on)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authbridge-lineage-config-${NAME}
  namespace: ${NAMESPACE}
data:
  config.yaml: |
    mode: envoy-sidecar
    pipeline:
      inbound:
        plugins:
          - name: a2a-parser
          - name: lineage-telemetry
            config:
              otel_endpoint: "otel-collector.kagenti-system.svc.cluster.local:4317"
              capture_io: true
              self_id: "${SELF_ID}"
      outbound:
        plugins:
          - name: inference-parser
          - name: mcp-parser
          - name: lineage-telemetry
            config:
              otel_endpoint: "otel-collector.kagenti-system.svc.cluster.local:4317"
              capture_io: true
              self_id: "${SELF_ID}"
---
apiVersion: v1
kind: Service
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: ${NAME}
    kagenti.io/type: ${KAGENTI_TYPE}
    protocol.kagenti.io/a2a: ""
spec:
  ports:
    - name: http
      port: ${SVC_PORT}
      protocol: TCP
      targetPort: ${APP_PORT}
  selector:
    app.kubernetes.io/name: ${NAME}
    kagenti.io/type: ${KAGENTI_TYPE}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: ${NAME}
    kagenti.io/type: ${KAGENTI_TYPE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${NAME}
      kagenti.io/type: ${KAGENTI_TYPE}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${NAME}
        kagenti.io/type: ${KAGENTI_TYPE}
        protocol.kagenti.io/a2a: ""
        # keep the operator's (broken, SPIRE-mounting) auto-injection OFF —
        # we inject our own sidecar below.
        kagenti.io/inject: disabled
    spec:
      containers:
        - name: agent
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          command: ${CMD_ARRAY}
          ports:
            - { containerPort: ${APP_PORT}, name: http }
          env:
${env_block}
          readinessProbe:
            tcpSocket: { port: ${APP_PORT} }
            initialDelaySeconds: 5
            periodSeconds: 5
        # lineage sidecar: Envoy + authbridge-envoy(ext_proc + lineage plugin).
        # MUST run as UID 1337 (excluded from the iptables outbound redirect).
        - name: envoy-proxy
          image: docker.io/library/authbridge-envoy:latest
          imagePullPolicy: IfNotPresent
          args: ["--config", "/etc/authbridge/config.yaml"]
          securityContext:
            runAsNonRoot: false
            runAsUser: 1337
            runAsGroup: 1337
          ports:
            - { containerPort: 15123, name: envoy-out }
            - { containerPort: 15124, name: envoy-in }
            - { containerPort: 9090,  name: ext-proc }
            - { containerPort: 9901,  name: envoy-admin }
          volumeMounts:
            - { name: envoy-config,       mountPath: /etc/envoy }
            - { name: authbridge-runtime, mountPath: /etc/authbridge }
      initContainers:
        - name: proxy-init
          image: docker.io/library/proxy-init:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP${exclude_env}
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
        - name: authbridge-runtime
          configMap:
            name: authbridge-lineage-config-${NAME}
            items:
              - { key: config.yaml, path: config.yaml }
EOF
